### ISSUE TITLE
Where are the translations done?

### ISSUE THREAD

**Issue by kghbln** [mockturtl/cinnamon-weather#104]
According to the homepage of this applet it is done here but the last translation update suggests otherwise. Should I just open a pull request?

**Comment by mockturtl** [comment]
> According to the homepage of this applet it is done here but the last translation update suggests otherwise. 

I'm sorry, I don't understand.

I really should make a CONTRIBUTING file. (#52)

> Should I just open a pull request?

Please do!

**Comment by kghbln** [comment]
Yeah a CONTRIBUTING file will be cool. Well you seem to be polyglot (https://github.com/mockturtl/cinnamon-weather/commit/28a25b2cd5745d111bb14a4dbd13e987815cf4b6) or the translation come from another source. ;)

Will do a pull-request.

**Comment by kghbln** [comment]
Done with this pull request: https://github.com/mockturtl/cinnamon-weather/pull/105
