### ISSUE TITLE
In-panel font

### ISSUE THREAD

**Issue by zagortenay333** [mockturtl/cinnamon-weather#110]
Not sure whether this is an issue with this applet or with something else, but I noticed that the font in the panel doesn't change from the default sans font. Here is another text applet next to it with the Droid sans font:
![screenshot from 2015-02-24 11 57 06](https://cloud.githubusercontent.com/assets/11144630/6347982/8836ae6a-bc1c-11e4-856f-c764b498ebeb.png)

**Comment by mockturtl** [comment]
> Not sure whether this is an issue with this applet or with something else

Please look into it and let me know.

**Comment by zagortenay333** [comment]
From what I can see it's the applets fault. I didn't manage to find any selector that can modify it, and all themes have the same issue.

**Comment by mockturtl** [comment]
I'm afraid I don't know much about fonts.  I can barely spot a difference between the letters "C" in your screencap.

How can I reproduce the problem?

**Comment by mockturtl** [comment]
> I didn't manage to find any selector that can modify it,

```sh
$ git grep font
# stylesheet.css:14:  font-size: 35px;
# stylesheet.css:58:  font-size: 90%;
```

**Comment by zagortenay333** [comment]
You are using the default theme; that one has the same sans font, so you can't see a difference. Try using one of my themes, which use the Droid Sans font.

I don't understand what that grep stuff is about. ._."

The only selector which right now has an effect on this is *.applet-label*, and I cannot change the font using it, only the color.

**Comment by mockturtl** [comment]
> Try using one of my themes

With [Numix-Cinnamon](http://cinnamon-spices.linuxmint.com/themes/view/196):

![screencap2](https://cloud.githubusercontent.com/assets/705804/6376728/baf4f57e-bced-11e4-8d4e-9a50509d06ac.jpg)

What should I be looking at?

**Comment by zagortenay333** [comment]
Hmm. Looking bit more closely, it seems that only the units "°C" ąnd "°F" are not the droid sans font. The number and conditions have the correct font.
Also numix-cinnamon
![screenshot from 2015-02-27 18 19 05](https://cloud.githubusercontent.com/assets/11144630/6417352/22bb4aa8-bead-11e4-9ca7-e732bd729ad4.png)

Notice how in your screenshot the F from the unit is not the same as the F from "Feb"

**Comment by mockturtl** [comment]
Eureka!  

![scap3](https://cloud.githubusercontent.com/assets/705804/6418674/1e053cd0-be85-11e4-8cd0-0146b25b5674.jpg)

They [are](https://github.com/mockturtl/cinnamon-weather/blob/6f5d27c853f7841bd1133cd9518c5907e85f4f01/applet.js#L786) different characters, in fact: [℃](http://www.fileformat.info/info/unicode/char/2103/index.htm) [℉](http://www.fileformat.info/info/unicode/char/2109/index.htm).

**Comment by mockturtl** [comment]
> Then again, at least in your case the font did change between the two themes you showed. In my case it stays the same no matter what theme I use.

Which version of Cinnamon are you running?  I'm on LMDE.

```sh
 $ cinnamon --version  # 2.0.14
```

**Comment by zagortenay333** [comment]
I'm running 2.4.6.

Well, if it's a unicode character then that would explain it I guess. Is there any reason for that, or can it just be normal text?

**Comment by mockturtl** [comment]
Localization, I guess.  It shouldn't translate the way a bare letter C/F would.

Maybe I'm not calling something I should be in 2.4 for a `TextApplet` to participate in system theming.  I'll look into that.

Can you take a screenshot of your panel showing the weather applet's font mismatched beside, say, the calendar applet?

**Comment by zagortenay333** [comment]
I wrote above that only the  °C character appears to be mismatched because its a unicode character. The rest looks fine.

You are right though, didn't think that a C in this case shouldn't be translated. I guess it should be left as is then.

**Comment by zagortenay333** [comment]
I guess this applet doesn't use a unicode character then: http://cinnamon-spices.linuxmint.com/applets/view/198

**Comment by mockturtl** [comment]
> The rest looks fine.

Am I correct in understanding there is no problem here:

> Then again, at least in your case the font did change between the two themes you showed. In my case it stays the same no matter what theme I use.

**Comment by mockturtl** [comment]
> I guess this applet doesn't use a unicode character then

See [here](https://github.com/pixunil/cinnamon-applet-system-monitor/blob/master/modules.js#L251), if I'm not mistaken.

**Comment by zagortenay333** [comment]
The weird thing is, you showed two screenshots there, one with then numix theme and one with the default theme, and the unicode °F did change as far as I can see. That doesn't happen on my machine. O_o

**Comment by zagortenay333** [comment]
Hmm, if both these applets use a unicode characther, how come the C's look different in my screenshot at the top?

**Comment by mockturtl** [comment]
I see what you're telling me: the horizontal legs of the '℉' are 1 vs. 2 pixels apart.

![](https://cloud.githubusercontent.com/assets/11144630/6417352/22bb4aa8-bead-11e4-9ca7-e732bd729ad4.png)
![](https://cloud.githubusercontent.com/assets/705804/6376728/baf4f57e-bced-11e4-8d4e-9a50509d06ac.jpg)

Maybe it's a bug in 2.4?

**Comment by mockturtl** [comment]
> if both these applets use a unicode characther, how come the C's look different

I [meant](https://github.com/mockturtl/cinnamon-weather/issues/110#issuecomment-76451550) that the source for the system-monitor applet uses the unicode degree symbol [°](http://www.fileformat.info/info/unicode/char/00b0/index.htm) + bare letter C/F.

**Comment by zagortenay333** [comment]
Yeah, I just figured that he only uses the ° unicode. I guess nothing can be done in that case.

Also, it seems that droid-sans doesn't support unicode, only droid sans fallback. That's why the °C is borrowed from the sans font in my themes.

**Comment by mockturtl** [comment]
> droid-sans doesn't support unicode, only droid sans fallback

That's good to know.  Thanks for reporting it.

**Comment by zagortenay333** [comment]
I might actually open an issue on the other guys applet to ask whether he could use the '°C' unicode instead of only '°'
