### ISSUE TITLE
weather applet loading with no output

### ISSUE THREAD

**Issue by sha-hin** [mockturtl/cinnamon-weather#116]
hello

I've installed weather applet but it didn't work at all.
always loading with no result or output.
I've tried punch of WOEIDs with no success.

I've cinnamon v2.4.8 
on Linux mint 17.1 Rebecca.

thanks in advance.

**Comment by mockturtl** [comment]
> I've tried punch of WOEIDs with no success

Which ones?

**Comment by sha-hin** [comment]
thank you for reply

I've tried EGXX0001,USSD0333,CAXX0504,CAXX2525,BRXX0885,.....etc

I've tried for different location and cities with no success.

**Comment by mockturtl** [comment]
Thanks, those work for me.

Do you use a proxy?  (Menu -> Network, or run in a terminal: `cinnamon-control-center network`)

**Comment by sha-hin** [comment]
No I don't use  a proxy.

**Comment by mockturtl** [comment]
Let's see if you can reach the API from a browser.  Does this link show you some data?

http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20feednormalizer%20where%20url=%22http://xml.weather.yahoo.com/forecastrss/EGXX0001_c.xml%22

**Comment by sha-hin** [comment]
Unfortunately, the link didn't work.
"Webpage not available".

**Comment by mockturtl** [comment]
You're having a network problem, then.

Maybe this will help?

https://support.google.com/chrome/answer/117805?hl=en

**Comment by sha-hin** [comment]
Thank you sir for your help.
I've tried all solution to get this link open but no avail.
Maybe the link is blocked in my country as I asked other two friends to try open it from different PCs but as usual not available even link "weather.yahoo.com" work perfectly so it's strange.
Best wishes.

**Comment by mockturtl** [comment]
> Maybe the link is blocked in my country 

That's my best guess right now.  Maybe you can try the link through a web-based proxy.

Good luck!
