### ISSUE TITLE
„Refreshweather" improvement

### ISSUE THREAD

**Issue by cranes-bill** [mockturtl/cinnamon-weather#120]
Hi,
First of all, thank you for the nice tool! :ok_hand: And also - sorry for my bad English! :flushed:
And now on the „_issue_“:
I'm using few networks, so the auto-connection is not set. But after manually connect to the network, it takes to much time to show the actual weather, probably because the update it was did on the booting of the system. As workaround i add the following on the settings:

```
, "refreshWeather":
  { "type": "button"
  , "description": "Update Weather"
  , "callback": "refreshWeather"
  , "tooltip": "Update Weather"
  }
```

But my idea is, if initial check can be delayed, or more better, but perhaps very hard to implementation, the `refreshweather` if can be executed, after the Internet connection established.
I'm just proposing the above, but i'm not familiar with Javascript, so sorry if it's none sense!I'll keep liking this applet, even without more improvements. :+1:
Kind regards!

**Comment by kehugter** [comment]
:+1: 
How about refreshing the weather when `(connection established) && (last update > update interval)`?
A button to update manually would be great too. It could be displayed optionally, configuring it in the settings.

**Comment by cranes-bill** [comment]
I'm closing this issue due to no answer.
Furthermore, the applet started to giving incorrect information and i stopped using it.

**Comment by kehugter** [comment]
@cranes-bill the issue wasn't solved nor rejected, please leave it open.

From https://github.com/mockturtl/cinnamon-weather/blob/master/CONTRIBUTING.md
>Feel free to @mention me in the issue comments if too much time has passed.

So here we go: @mockturtl, could you take a look at this?

**Comment by cranes-bill** [comment]
@kehugter,
 Sorry, i'm reopening it just for you!

**Comment by mockturtl** [comment]
> I'm closing this issue due to no answer.

As a matter of GitHub etiquette, don't do that.  Prefer the "Unsubscribe" button, on the right.

> Furthermore, the applet started to giving incorrect information

That discussion belongs here: #127

----

@kehugter

> How about refreshing the weather when (connection established) && (last update > update interval)?

I don't know how to discover the network state.  The network manager applet's code could be instructive; please do investigate.

I think a refresh button on the left-click popup menu would be nice.  But the learning curve is pretty steep.

http://developer.linuxmint.com/reference/index.html

As a workaround, notice that updating any setting will force a reload.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
