### ISSUE TITLE
Estonian Locations incomplete support

### ISSUE THREAD

**Issue by vaikus84** [mockturtl/cinnamon-weather#124]
Hello

Reporting that Estonian locations support is not complete in the application. Although for example weather.com finds those places without issues.

Example:

ENXX0004	Tallinn, Estonia +
ENXX0201	Vaskjala, Estonia -
ENXX0682	Lehmja, Estonia -
ENXX0024	Arukula, Estonia -
ENXX0005	Tartu, Estonia +
ENXX0010	Turi, Estonia +
ENXX0352	Parnu-Jaagupi, Estonia -
ENXX2776	Parnu, Estonia -
ENXX0388	Rapla, Raplamaa -
ENXX3323	Kohila, Raplamaa -
ENXX3309	Kehtna, Raplamaa -

- minus means not working in the app
+ plus means working in the app

As you can see. The codes are there and at least Weather.com seems to get info on them.

Thank you for your efforts and I hope you can improve your app :)

**Comment by mockturtl** [comment]
Hi @vaikus84,

> weather.com finds those places without issues

Indeed, Yahoo! Weather doesn't seem to know those locations.  See here:

<https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city>

Contributions to use a different service are most welcome.

**Comment by vaikus84** [comment]
I propose http://www.wunderground.com/weather/api/d/docs?d=autocomplete-api.
Hope you are getting this. Better at Locating Estonian Local places. Also universal because lots of Android widgets use it.

**Comment by vaikus84** [comment]
If I'm not mistaken you need this one  http://www.wunderground.com/weather/api/d/docs?d=index    ?
