### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by AcostArichA** [mockturtl/cinnamon-weather#126]
Hi! I have LM 17.2. How can one make his native language to work for its applet? For me it is Russian. At settings I see only 'Translate condition' but it isn't translate at my language. Thank You.

**Comment by mockturtl** [comment]
Hi @AcostArichA,

As far as I know, an applet should automatically use your system language, if a suitable translation file is available.  ([here](https://github.com/mockturtl/cinnamon-weather/blob/master/po/ru.po))

Do you have Russian installed and selected _(Menu -> Languages)_?

If that doesn't fix it, someone on the IRC (Spotchat, #linuxmint-help) or the applet's [mailing list](https://groups.google.com/forum/#!forum/cinnamon-weather) can probably help.
