### ISSUE TITLE
Weather applet buggy displaying wrong day

### ISSUE THREAD

**Issue by Johnny-John** [mockturtl/cinnamon-weather#127]
Linux Mint 17.2 Cinnamon desktop
Weather applet displaying different days as today, usually wrong, generally from the past. Seemingly random, sometimes at the update interval, or at other times when a setting is toggled, the day will shift to another (usually incorrect "today"). Thought I would report it since a lot of people use it and enjoy it quite a bit. Thanks.

**Comment by mockturtl** [comment]
Thanks for the report.  It looks like Yahoo is having some problems.

https://groups.google.com/forum/#!topic/cinnamon-weather/5cGdo0dHaSk

**Comment by loomsen** [comment]
Hi, I'm having the same troubles. It's showing 10°C when it's snowing outside, so the data is completely off. And this is for Hamburg, the 2nd largest city in Germany. Maybe a rewrite would be useful, where the providers could be added as modules or plugins, so people could write plugins for their preferred provider?
That would be awesome.

**Comment by mockturtl** [comment]
Meanwhile: https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

**Comment by cstoudt** [comment]
I'm having the same issue.

Linux Mint 17.2 Cinnamon 64-bit, Cinnamon Version 2.6.13, Kernel 3.16.0-38 generic, Weather applet 1.9.9

The panel applet displays the correct weather information at startup. When the computer goes into sleep or hibernation and then resumes, the weather app displays weather information that appears to be that for several days previous and doesn't update according to the update interval. It requires logout/logon to restore the correct information.

I've noted this behavior on both a laptop and a desktop, both running the same version of Mint/Cinnamon.

**Comment by loomsen** [comment]
It's yahoos fault. Mine seems to be fine today.

**Comment by ccprog** [comment]
According to my log (produced by [this](https://github.com/ccprog/cinnamon-weather) fork), starting with midnight GMT+0100, all data delivered were clean. We'll have to watch it for a few days, but it seems Yahoo was able to fix the problem.

**Comment by tomgeor** [comment]
I still see this a lot, are we sure it's fixed?

**Comment by mockturtl** [comment]
As far as I can tell, the data is correct now.

**Comment by santa-klaus** [comment]
I am sorry, but I still have that problem. I installed it today and it is showing the data for yesterday...
My WOEID is SWXX0007.

**Comment by ccprog** [comment]
More like again. Yahoo data seem to be stuck since Monday evening - I permanently get Mon Apr 11 2016 18:49:00 GMT+0200 (CEST).

**Comment by loomsen** [comment]
I second that, stuck on Monday here too.

**Comment by santa-klaus** [comment]
I am also still on monday, but I can´t check the exact time. However, temperature has changed from 12 to 13 degrees since yesterday.

**Comment by ccprog** [comment]
I suspect Yahoo is changing things around for its API - like always without telling anyone about it: https://forum.rainmeter.net/viewtopic.php?f=13&t=23010.

Currently, I don't get the URL used by the applet to work. This URL gets a valid response:

```http://query.yahooapis.com/v1/public/yql?format=json&q=select * from weather.forecast where woeid=#LocationCode# and u="#Unit#"```

Exchanging `#Unit#` for `f` or `c` and `#LocationCode#` for the WOEID - BUT this seems to have changed, too: Formerly I was using "GMXX0007" for Berlin, Germany. Now, I have to use "638242".

Currently, the Applet guides to https://weather.codes/ to select the WOEID. There you will get the old numbers. I got the new ID from http://woeid.rosselliot.co.nz.

In addition, the returned JSON object has a slightly changed format. Old:
```{ "query": { "results": { "rss": { "channel": { ... } } } } }```
New:
```{ "query": { "results": { "channel": { ... } } } }```

Now, anyone ready to make a guess how long this will be working?

**Comment by loomsen** [comment]
Why don't we move to openweather? http://openweathermap.org/api

**Comment by ccprog** [comment]
Because they are IT professionals and "meteorological enthusiasts" (http://openweathermap.org/about), not meteorologists?

> OpenWeatherMap has its own model of weather calculation.

I am weary of hobbyists saying something like this...

**Comment by loomsen** [comment]
Right. Will be hard to find something free for the masses, though. I guess...

**Comment by santa-klaus** [comment]
Well, thanks for the commit, I hope that will change it. However, if I use the new WOEID (full numeric) with the existing version of the applet, I don´t get any data at all - while with the old ID I get at least data from some past date. Not sure if thats a thing you fixed in the commit, but thought it would make sense to share that information.

**Comment by jukaZG** [comment]
Is there a way to replace Yahoo API with Yr.no API? It is an great weather site form Norway.

**Comment by santa-klaus** [comment]
Is there anything going to happen? My applet still won´t work...

**Comment by loomsen** [comment]
Wetter.com also seems to be working on some openweather API for non commercial use.

https://api.wetter.com/files/wetter.com_openweather_api.pdf
(in german...)

**Comment by ccprog** [comment]
The wetter.com website is currently incomplete because of an overhaul. Therefore I sent them an email asking for details whether the openweather API could be used for a CInnamin desktop applet. The conversation was in german, so I'm paraphrasing the answer:

- The API website is under construction, new projects currently cannot be added.
- The openweather API is free of charge only for private projects and websites.
- wetter.com would insead be prepared to deliver weather data through thier commercial RWDS interface, for which I got sent a price list. Prices depend on the number of calls through the API and start with 50 € for less than 1000 calls per month.

**Comment by loomsen** [comment]
http://api.daswetter.com/
What about this?

"Sie können diese Informationen für Handy-Apps, Fernseh- oder Radioprogramme, Zeitungen, etc., auch für das Internet vollkommen kostenlos nutzen."

**Comment by ccprog** [comment]
yr.no has current conditions only for places in Norway, internationally it provides only forcasts. daswetter.com (or rather, tiempo.com) seems to only provide forecasts, I could not find current conditions at all.

**Comment by jukaZG** [comment]
So what is the best solution to have somehow working applet? 
How could I manage to add anything to my applet to have temperature at the moment, etc.?
