### ISSUE TITLE
Different weather than weather.yahoo.com

### ISSUE THREAD

**Issue by gilbertohasnofb** [mockturtl/cinnamon-weather#130]
Since a couple of days the weather applet is showing wrong information. For instance, right now it reads 14 degrees Celsius for EZXX0012 (Prague, Czech Republic), https://weather.yahoo.com/ gives the correct temperature of 1 degree Celsius. 
I also noticed that sometimes the applet suddenly displays the right information (including the 5 days forecast), but shortly after returns to the wrong values.

**Comment by mockturtl** [comment]
> Since a couple of days the weather applet is showing wrong information. 

It seems so.  Several people have reported this behavior.

Yahoo is returning last week's weather for your location.  See here:

https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

Thank you for the report.  Hopefully it will be fixed soon.

**Comment by mockturtl** [comment]
Duplicates #127.

**Comment by gilbertohasnofb** [comment]
Thank you for the fast reply, let's hope Yahoo fixes this soon.
