### ISSUE TITLE
WOEID - new codes update

### ISSUE THREAD

**Issue by 4t4h3cl** [mockturtl/cinnamon-weather#134]
As stated [here] (https://docs.rainmeter.net/tips/webparser-weather-location-code/), Yahoo is doing some upgrades of WOEIDs ... and for my case, the old format of WOEID did not work with the existing code, thus i've adjusted it to the new format.

The needed changes to make things work are in the applet.js:

**New URL for WOEID lookup**:

const WOEID_URL = "http://woeid.rosselliot.co.nz/"

**Changed parameter**:

const QUERY_TABLE = 'feednormalizer where url="http://xml.weather.yahoo.com/forecastrss?w='

**unitToUrl function:**

return this._temperatureUnit == WeatherUnits.FAHRENHEIT ? '%26u%3Df' : '%26u%3Dc'

**weatherToUrl function:**

let output = QUERY_URL + this._woeid + this.unitToUrl() + '"'

**Comment by Tomaszm700** [comment]
I put here an information how to check your actual WOEID - may help someone as well.
[https://github.com/mockturtl/cinnamon-weather/issues/138](url)

**Comment by icemodding** [comment]
Argentina, Nor Buenos Aires, Cordoba, etc. - Cities or not loaded directly on San Miguel de Tucuman not appear :( 

ice@ice ~ $ cinnamon --version
Cinnamon 2.8.7

**Comment by mockturtl** [comment]
<https://developer.yahoo.com/weather/>

> To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting **March 15, 2016**. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret.

@icemodding Was it OK before?  Please give me a WOEID to try.

**Comment by mockturtl** [comment]
[more: tipichris/bbcwx#24](https://github.com/tipichris/bbcwx/issues/23#issuecomment-205880268)

**Comment by tonywhelan** [comment]
> To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret.

This appears to be saying that the data is no longer freely available without a Yahoo key and secret? So the weather applet will no longer function?

**Comment by ienev** [comment]
Due to the changed WOEID values it seems the applet doesn't work anymore. For example for Sofia, Bulgaria the old code was BUXX0005 but now it displays the temperature for Sunnyvale, CA which I suppose is some kind of default one if the API can't find the WOEID. I've entered the new code 839722 but it doesn't seem to work as probably the endpoint is changed or requires authentication.

**Comment by Matt832** [comment]
Applet stopped working for me recently too.  I'm in the US, changing zip code has no effect.  Miss the weather info, wish it would work again.

**Comment by cranes-bill** [comment]
Yeah, i can confirm the applet stopped working.
@mockturtl, [here](https://cinnamon-spices.linuxmint.com/desklets/view/20) is a desklet, which uses `BBC Weather` . Can you replace the source with it?

**Comment by vlatkoB** [comment]
Applet is working, but it's data source isn't.

This is url for Zagreb, Croatia (which applet is constructing):


`http://query.yahooapis.com/v1/public/yql?format=json&q=select * from feednormalizer where url="http://xml.weather.yahoo.com/forecastrss/HRXX0005_c.xml"`

and the data is from 5 days ago (today).
 "lastBuildDate": "Mon, 11 Apr 2016 7:00 pm CEST",

**Comment by 4t4h3cl** [comment]
I've managed to make it work for me by altering a few lines in the applet.js code.
New URL looks like this:

https://query.yahooapis.com/v1/public/yql?q=select+*+from+weather.forecast+where+woeid=532284+and+u=%27c%27&format=json


Attached applet.js is from me, please make a diff or something to see the changes.
Basicaly the only thing that changes is the URL format and this line (removed the rss get object)
let weather = json.get_object_member('query').get_object_member('results').get_object_member('channel')

[applet.txt](https://github.com/mockturtl/cinnamon-weather/files/222599/applet.txt)

**Comment by tonywhelan** [comment]
Thanks for the effort you've made here. Result looks good initially (with the new woeid codes) but the 5-day forecast for Canberra AU seems several degrees below what the local forecast says, and what accuweather says. Pressure looks wrong and wind chill is crazy (54C!??). So maybe there is more to this than just those changes you've made? I wish I had the time to have a go at this myself but have too many other responsibilities for next couple of weeks.

**Comment by 4t4h3cl** [comment]
Maybe because i've added the temperature unit in Celsius into the URL?
My forecast seems OK, comparing the one from forecast.io and this one (Yahoo).

The pressure seems way off, but i don't care much about pressure... :)

**Comment by tomgeor** [comment]
Running into the same thing here but I've only tried changing settings or woeids.

**Comment by ScottGeiger** [comment]
I had not seen this before starting to make edits as well.  I made similar changes as @4t4h3cl did can confirm it is now working.

I changed as follows:
(at line 60): 
`// Query
const QUERY_PARAMS = '?format=json&q=select '
//const QUERY_TABLE = 'feednormalizer where url="http://xml.weather.yahoo.com/forecastrss/'
const QUERY_TABLE = 'weather.forecast '
const QUERY_VIEW = '*'
const QUERY_URL = 'http://query.yahooapis.com/v1/public/yql' + QUERY_PARAMS + QUERY_VIEW + ' from ' + QUERY_TABLE`

(at line 389):
`      try {
        //let weather = json.get_object_member('query').get_object_member('results').get_object_member('rss').get_object_member('channel')
        let weather = json.get_object_member('query').get_object_member('results').get_object_member('channel')
        let weather_c = weather.get_object_member('item').get_object_member('condition')
        let forecast = weather.get_object_member('item').get_array_member('forecast').get_elements()
`

(at line 802):
`, weatherUrl: function weatherUrl() {
    //let output = QUERY_URL + ' where location="' + this._woeid + '" and u="' + this.unitToUrl() + '"'
    //let output = QUERY_URL + this._woeid + '_' + this.unitToUrl() + '.xml"'
    let output = QUERY_URL + ' where woeid=' + this._woeid
    return output
`

**Comment by brianjmurrell** [comment]
I get a ```￼504 Gateway Time-out``` trying to access http://woeid.rosselliot.co.nz/ to get a new WOEID to use with @ScottGeiger's new applet.
￼

**Comment by ScottGeiger** [comment]
I don't have any issue getting to that site.  You can also try Yahoo's YQL test page: https://developer.yahoo.com/yql/console/?q=select%20woeid%20from%20geo.places(1)%20where%20text%3D"nome%2C%20ak"&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys#h=select+woeid+from+geo.places(1)+where+text%3D%22nome%2C+ak%22

As a last resort you could Google it, but there are some incorrect (possible old) WOEIDs out there.

**Comment by brianjmurrell** [comment]
@ScottGeiger: Yeah, I got there after a retry.  Deleted my comment also.  :-)

But I have to say, Yahoo's weather is garbage (now).  Even going to their own page https://ca.news.yahoo.com/weather/<country>/<state|province>/<city-*>/ shows completely inaccurate weather.

Google shows much more realistic weather.

**Comment by mockturtl** [comment]
duplicates #127
