### ISSUE TITLE
Mint 17.3 No Data query

### ISSUE THREAD

**Issue by Tomaszm700** [mockturtl/cinnamon-weather#138]
Applet do not query any informations. After installation applet show it self in bar but it looks like waiting for informations ( round arrow icon )
I check all the settings with few location codes - no changes.

**Comment by mockturtl** [comment]
Which applet version?

The first step is to check your location codes in a browser.

https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

If those results look OK, do you use a network proxy?

**Comment by Tomaszm700** [comment]
Thanks a lot for replay - **Problem found and it is not on side of applet**. I test lot of WOEID codes and only huge Cities codes respond with data. My apologize for rising problem that in fact comes not from app code.
Im wonder of one more thing WOEID applet is using format PLXX0040 ( Poznan, Poland ) I try to find WOEID of my little town and yahoo shown WOEID in this format 514048 ( Poznan, Poland) on Yahoo weather even my little town weather is shown (518783). Is it possible that yahoo use two databases and we are using this non fully updated or supported? and if yes can we change it somehow to make available all locations info?

**Comment by Tomaszm700** [comment]
I just found how to find correct working WOEID for own location - I hope this will help someone.

1. open this web page [http://zourbuth.com/tools/woeid/](url)
2. Put name of your location ( in this exaple I will use town called Slupca in Poland )
3. List of location will be shown in respond
**Details			                                WOEID
Slupca	Poland	Greater Poland	518783
Slupca	Poland	Greater Poland	29397281
Slupca	Poland	Masovian	                518784
4. Copy your location WOEID ( in my case 518783 or 29397281 will be correct one )
5. Now put this address in your browser http://weather.yahooapis.com/forecastrss?w=location
and change last word **location** to copied before number, so it will looks like this
http://weather.yahooapis.com/forecastrss?w=518783
6. Pusch Enter

In respond you will se an generated Code in line 4 you will see 
<title>Yahoo! Weather - Slupca, PL</title> this confirm your location
In line 5 
<link>
http://us.rd.yahoo.com/dailynews/rss/weather/Slupca__PL/*http://weather.yahoo.com/forecast/PLXX0066_f.html
</link>
As you can see on the end of the line there is a code in right format PLXX0066 
This is code of closest Measuring point to your location 
7. Paste it in to applet WOEID editbox
8. Set your location label in the bottom of settings tab
