### ISSUE TITLE
WOEID EZXX0405 not work

### ISSUE THREAD

**Issue by vaclavpavek** [mockturtl/cinnamon-weather#139]
Hi, my WOEID EZXX0405 for Chrudim, Czech Republic not work. But EZXX0034 is OK (Pardubice, Czech Republic). Please help me set up the applet. Thanks

**Comment by mockturtl** [comment]
@vaclavpavek It looks like Yahoo has no data for EZXX0405.  You can confirm here:

https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

I [see](https://www.openstreetmap.org/search?query=chrudim#map=13/49.9984/15.7762) Pardubice is only a few km away.  I suggest using code EZXX0034, and maybe fix the city name with the "Override location label" setting.

**Comment by vaclavpavek** [comment]
Yahoo has no data for EZXX0405 :-( Thanks
