### ISSUE TITLE
not displaying the correct weather

### ISSUE THREAD

**Issue by brianjmurrell** [mockturtl/cinnamon-weather#145]
The weather is plain wrong here.  WOEID CAXX0225 is showing -1/6 C with showers.  It is sunny and 22C here right now.

What is the weather source for this WOEID?  I heard some grumblings about Yahoo Weather having gone through some changes lately.  Maybe that's got something to do with it.

**Comment by ScottGeiger** [comment]
It looks like it's a problem on the Yahoo end.  If you extract the URL out that retrieves the weather XML data you will see that the lastPubDate is old.  For my WOEID the last pub date shows as April 11.  It has not updated since then.

**Comment by brianjmurrell** [comment]
So what is the resolution to this problem?

**Comment by ScottGeiger** [comment]
@brianjmurrell - see issue #134 for a fix.

**Comment by brianjmurrell** [comment]
This is clearly a duplicate of issue #134.
