### ISSUE TITLE
No weather info. displayed at all

### ISSUE THREAD

**Issue by mattst** [mockturtl/cinnamon-weather#146]
The applet is now not working at all for lots of users.

Please see [this thread on the Linux Mint forums](https://forums.linuxmint.com/viewtopic.php?f=212&t=220308) which has more info. and a suggested fix.

Hope this helps.

**Comment by NathanSalapat** [comment]
I can confirm that the applet isn't working.

**Comment by marceloavan** [comment]
I think the PR #143 contains the solution of theses problems.

**Comment by mattst** [comment]
@marceloavan Thanks that fixed it.

For those unsure - you need to download the zip file on this page:

https://github.com/ccprog/cinnamon-weather/tree/ccprog-yahoo-new-format

and replace the contents of the `~/.local/share/cinnamon/applets/weather@mockturtl` directory with the contents of the zip file's `cinnamon-weather-ccprog-yahoo-new-format` directory.

Hope this helps.

**Comment by santa-klaus** [comment]
Thanks for the step-by-step tutorial, that helped a lot!

**Comment by Zerophase** [comment]
Hmm. Tried this fix, hitting refresh doesn't still work. Running on Cinnamon 3.0 though.

**Comment by sukosevato** [comment]
I'm running on Cinnamon 3.0 as well and it works for me just fine. 

I didn't try the ccprog-yahoo-newformat branch but used the branch which is most current of ccprog which is this:

https://github.com/ccprog/cinnamon-weather/archive/ccprog-yahoo-band-aid.zip

@Zerophase  be sure to use the new correct woeid format:

(Amsterdam, Netherlands)
New format: 727232 
Old format: NLXX0002

http://woeid.rosselliot.co.nz/lookup/Amsterdam

**Comment by Zerophase** [comment]
Turns out I just needed to reconfigure everything in settings.

**Comment by mockturtl** [comment]
duplicates #127
