### ISSUE TITLE
RU locale is broken?

### ISSUE THREAD

**Issue by IamLosted** [mockturtl/cinnamon-weather#148]
Cannot add an applet to panel. There is an error message in glass.log though:
`error t=2016-04-25T10:13:30.315Z Failed to convert UTF-8 string to JS string: Недопустимая последовательность байтов во входных преобразуемых данных
trace t=2016-04-25T10:13:30.315Z 
<----------------
dgettext@resource:///org/gnome/gjs/modules/gettext.js:49
_@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:206
showLoadingUi@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:626
rebuild@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:630
_init@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:317
MyApplet@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:218
main@/home/aleskovets/.local/share/cinnamon/applets/weather@mockturtl/applet.js:1047
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:329
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:256
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:197
---------------->
error t=2016-04-25T10:13:30.315Z [Applet "weather@mockturtl"]: Failed to evaluate 'main' function on applet: weather@mockturtl/41
error t=2016-04-25T10:13:30.315Z Could not load applet weather@mockturtl`

Seems like this is some issue with the load of localized strings.

**Comment by mockturtl** [comment]
@IamLosted Can you update to the latest release (1.13.0) and tell me what happens?

**Comment by IamLosted** [comment]
Works just fine now. Thanks!

**Comment by mockturtl** [comment]
Great!
