### ISSUE TITLE
try enter number, dont update data

### ISSUE THREAD

**Issue by denegny** [mockturtl/cinnamon-weather#149]
after update
USNY0996 - no data

version - 1.12.4
Cinnamon 2.8.8

**Comment by mockturtl** [comment]
@denegny Yahoo seems to require different WOEID codes now.  See here: https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

[example](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%222459115%22%20and%20u=%22c%22)
