### ISSUE TITLE
State licence and copyright holders for the project

### ISSUE THREAD

**Issue by ccprog** [mockturtl/cinnamon-weather#151]
I'm assuming this was a simple error at the time, but with 566c764dff2faaa564c789bf931e94bc903e6f07 you deleted the GPLv3 licence and copyright notices from this project.

As this was not allowed by the licence, please re-insert it.

**Comment by mockturtl** [comment]
I believed at the time, and still do, that copyleft is inappropriate for this script.  See "Small programs," here: http://www.gnu.org/licenses/license-recommendations.en.html

> It is not worth the trouble to use copyleft for most small programs. We use 300 lines as our benchmark: when a software package's source code is shorter than that, the benefits provided by copyleft are usually too small to justify the inconvenience of making sure a copy of the license always accompanies the software.

As you point out, the GPL seems to prohibit me from correcting the error.  Consequently, and meaning no disrespect to previous authors, I choose not to endorse it.

The complete contribution history is, of course, freely available for anyone to read, run, modify, or redistribute as he likes.

**Comment by ccprog** [comment]
I learned something new today - I had never heard about that 300 lines benchmark.

Now I could point out that the program is at 1000 lines...on the other hand, I am not a friend of the GPL myself, especially because of the rigidity of the way copyleft is handled. I came up with the issue mainly because I missed any sort of statement about copyright, and most importantly mentioning the names of the authors.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
