### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by ledzgio** [mockturtl/cinnamon-weather#153]
I cannot get information about my city using this:

http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20feednormalizer%20where%20url=%22http://xml.weather.yahoo.com/forecastrss/QAXX0003_c.xml%22

I get an error in JSON string:

"results":{"error":"XML parsing error at line: 14, column: 3. The element type \"HR\" must be terminated by the matching end-tag \"</HR>\"."}

**Comment by mockturtl** [comment]
> I get an error in JSON string:

Same here.  Thank you for the report.

I've updated the [wiki][].  Please try the new URL.

[wiki]: https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

**Comment by yoosefi** [comment]
Tried the new URL manually, it works. Tried updating the script to use the manual URL with XML format on line 803. Doesn't work.

**Comment by yoosefi** [comment]
see pull #155
