### ISSUE TITLE
Problems with pressure readings

### ISSUE THREAD

**Issue by msrego** [mockturtl/cinnamon-weather#157]
With the new Yahoo API format, the applet gives wrong pressure readings (e.g. 33.8555 atm).

I read in cinnamon-spices applet page some comments that mention that the API readings are returned with wrong units. They seem to be set to mbar.

Edit: Cinnamon 2.6.13 and applet version 1.12.5

**Comment by CyberTailor** [comment]
Example of **very** big pressure (25425 mm Hg)

http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%2290563928%22%20and%20u=%22c%22

How about using other weather providers (e.g yr.no, OpenWeatherMap)?

**Comment by msrego** [comment]
@CyberTailor
I would even suggest to have a list of providers to choose from in the settings window, as that would give the user the possibility to choose the provider that suits his needs (in terms of accuracy of data, etc).

I don't know if such change is difficult to implement, but it would be a very nice feature to have in the applet.
