### ISSUE TITLE
Wrong pressure in mmHg

### ISSUE THREAD

**Issue by sakralbar** [mockturtl/cinnamon-weather#163]
Hello!
The weather widget show 25679 mmHG, but now it only 758.
![2016-07-13 13 45 05](https://cloud.githubusercontent.com/assets/11180735/16800962/a1e60fc8-4900-11e6-8bf8-e4f97e5d76c3.png)

**Comment by mockturtl** [comment]
Hi!  красивые Калашн!

1. Is the value wrong in different units?  I wonder if the weather service just sent bad data.  For me, it displays and [converts](https://www.google.com/#q=1+in+in+mm) correctly (29.71 inHg, 755 mmHg).
1. Please tell me your Cinnamon version and applet version.

**Comment by sakralbar** [comment]
Thanks)

1. Yes, in inHg (1005), atm(33,5) and kPa (3403) wrong values too. Now in my city 754 mmHg, in applet -  25527. But one time apllet show correct value in inHg when I select it. After this wrong values again.
2. Cinnamon 3.0.6, applet 1.12.5

Sorry for my english.

**Comment by mockturtl** [comment]
Updating the applet should fix it.  Yahoo's pressure data is now wrong by a constant factor of 0.0295; this was fixed in version 1.13.1.  (see 6fadef3)

You can check the data here: https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

**Comment by sakralbar** [comment]
Yes, after update all ok, thank you.
