### ISSUE TITLE
Weather only shows Loading,,,

### ISSUE THREAD

**Issue by ibm1130** [mockturtl/cinnamon-weather#165]
Currently Fedora 24. Cinnamon weather 1.8.7

I saw a previous post but it is closed.  

I followed the instructions listed to test check prxy.

No proxy.

The suggested URL to try: http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20feednormalizer%20where%20url=%22http://xml.weather.yahoo.com/forecastrss/EGXX0001_c.xml%22

produced this line:
{"query":{"count":1,"created":"2016-08-11T23:04:12Z","lang":"en-US","results":{"error":"Unable to process url. Read timed out"}}}

I have tried USKS0572, USKS0358, and USMO0461

I have no ideas and have not found other suggestions.

John McKee

**Comment by mockturtl** [comment]
Hi John,

It looks to me like Yahoo weather knows some of those locations, but not others.

https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

- [EGXX0001](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22EGXX0001%22%20and%20u=%22c%22) fails
- [USKS0572](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22USKS0572%22%20and%20u=%22c%22) OK
- [USKS0358](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22USKS0358%22%20and%20u=%22c%22) fails
- [USMO0461](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22USMO0461%22%20and%20u=%22c%22) OK

> Currently Fedora 24. Cinnamon weather 1.8.7

That's a really old applet version.  Can you update?  What version of Cinnamon do you have?

Note Yahoo's API had breaking changes a few months back, and we use a different source for WOEID's now.

**Comment by ibm1130** [comment]
Cinnamon 3.0.1

Now getting more confused.  I did a comple update from Fedora 23 to Fedora 24.  I have performed several update since then.  Looking at the list of installed applets there is nothing indicating the version.  When I right click on the area where temperature should be, and left-click on about, that is wheer I see 1.8.7.  Is this then an issue with Fedora 24 not being current?

**Comment by ibm1130** [comment]
When I click on the more information tab, firefox opens a page stating 1.13.3

John McKee

**Comment by ibm1130** [comment]
The tab I am referring to is seen when looing at the list of installed apps.  That is where the link to the page exists.

John McKee

**Comment by mockturtl** [comment]
> When I right click on the area where temperature should be, and left-click on about, that is wheer I see 1.8.7.

Gotcha.  Click "Refresh list" here, and you should see an update available.

![screenshot from 2016-08-13 17 50 47](https://cloud.githubusercontent.com/assets/705804/17645827/81fcbb76-617e-11e6-9df7-66d0ed18cb14.png)

**Comment by ibm1130** [comment]
Thank you.  Never occurred to me to do that, as I believed the upgrade would have done that.  I have older Fedora installed on a few computers.  I have no idea who prepared the weather applet before Gnome changed and Cinnamon got started.  That old weather program still works.  It could dsplay the radar if available, as well as the forecast in text.  Also weather alerts.  I miss that.

But, just seeing weather again is a very nice experience.

**Comment by mockturtl** [comment]
You're welcome.  I'm glad it's working for you.
