### ISSUE TITLE
Change The Wind Chill Label

### ISSUE THREAD

**Issue by SerafDosSantos** [mockturtl/cinnamon-weather#169]
The 'Wind Chill' label should be 'Felt Temp.' where in summer humidity is the factor to make the temperature higher, and in winter, wind and humidity drops it.

**Comment by mockturtl** [comment]
I don't think the Yahoo! API provides a "heat index" value.   [test][] | [docs][]  

The [calculation][calc] is somewhat convoluted, but I welcome a pull request if someone wants this feature.

"[Apparent temperature][apparent]" seems to be more art than science.  [In the US][nws], it means wind chill below 50°F, and heat index above 80°F.  [Australia][aus] uses more variables.  Is there a global standard?

[test]: https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city
[docs]: https://developer.yahoo.com/weather/documentation.html
[calc]: https://en.wikipedia.org/wiki/Heat_index#Formula
[apparent]: https://en.wikipedia.org/wiki/Apparent_temperature
[nws]: http://www.nws.noaa.gov/ndfd/definitions.htm
[aus]: http://planetcalc.com/2089/

**Comment by SerafDosSantos** [comment]
I don't know of global standards as I'm a simple user of the applet. Although I observed this summer that the Wind Chill label was indicating higher temperatures due to humidity as I guess that the Yahoo API already calculates these estimations. So the label is a little misguiding. There's really no rush on my side as winter is coming and the Wind Chill label will have its full sense. Try to observe on your side if higher temperatures hits your town and I think you'll see what I mean.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
