### ISSUE TITLE
Couple of issues...

### ISSUE THREAD

**Issue by stunito0o0o0** [mockturtl/cinnamon-weather#170]
Hello,
first I want to thank you guys for the awesome applet.
So about the issues, as you can see from the screenshot below, I am using a macbuntu theme and a 7 day forecast. All works well except for the weather dialog not being centered, which i know is not a big deal, but it annoys me lol. The second thing  is that the day forecast text is not black, but some green-ish color, which i tried to look for and change int the applet css file, but i was unable to find, so I think it is inherited from the theme. Is there a way to fix those issues? I am a newbie so please go easy on me :)
![untitled](https://cloud.githubusercontent.com/assets/21028278/20869386/1f3377c8-ba7a-11e6-8fc9-7d9cecd22c9b.png)

**Comment by mockturtl** [comment]
Please tell me your distro, Cinnamon version, and applet version.

>  a macbuntu theme 

I don't know anything about that.  Is it [one of these][spices]?  Have you tried other themes?

[spices]: https://cinnamon-spices.linuxmint.com/themes

**Comment by stunito0o0o0** [comment]
I am using mint 18

**Comment by stunito0o0o0** [comment]
oh and this is what i use for theme settings
![image](https://cloud.githubusercontent.com/assets/21028278/20869594/4b297266-ba7e-11e6-905f-a721bf9bda6c.png)

**Comment by mockturtl** [comment]
I think it's a problem with your theme.  You might want to report it to them.

> Note: If you encounter any bug in theme/icons/any stuff, report to us with screenshot or problem with details.

Alternatively, check out the "Add/remove desktop themes..." link (bottom of your screenshot).

**Comment by stunito0o0o0** [comment]
I will try to change the theme and report back to you. Thanks

**Comment by stunito0o0o0** [comment]
> Cinnamon controls panel layout, not the individual applet.
Okay, so how can I fix it?

**Comment by mockturtl** [comment]
> Okay, so how can I fix it?

You can report it to [Cinnamon](https://github.com/linuxmint/cinnamon/issues), but I think it's a pretty unusual request.  Why do you expect a tooltip to be centered?

**Comment by stunito0o0o0** [comment]
Well I like symmetry, I don't see anything wrong with that.
