### ISSUE TITLE
The applet is missing atmospheric pressure in hPa

### ISSUE THREAD

**Issue by artscoop** [mockturtl/cinnamon-weather#171]
hPa and inHg (US only) are essentially the only 2 units in use for atmospheric pressure.
hPa is not supported by the applet.
I don't know if it's a feature request or a bug report.

**Comment by mockturtl** [comment]
1 hPa = 1 mbar

What's the problem?

**Comment by mockturtl** [comment]
> The millibar is still often used in weather reports and forecasts for the public, but the term hectopascal is increasingly being used, especially on the Continent in general and France, in particular.

http://weather.mailasail.com/Franks-Weather/Hectopascals-And-Millibars

> While hPa is used in meteorology most weatherforecasts quote atmospheric pressure in millibar.

http://www.weatheronline.co.uk/reports/wxfacts/Millibar-and-hectopascal.htm

**Comment by artscoop** [comment]
Oh, sorry. My bad.
Thanks!
