### ISSUE TITLE
Applet day forecast not centered

### ISSUE THREAD

**Issue by stunito0o0o0** [mockturtl/cinnamon-weather#172]
Hello, I am sorry for making a new  thread, but you closed the [previous one](https://github.com/mockturtl/cinnamon-weather/issues/170) and didn't let me post an update with the stock theme.

So, as promised, I made a fresh install of mint 18 on a virtual machine, I downloaded the applet, and put it in che center part of the panel. As you can see It is still not centered, so this is a problem with the applet and not the theme.

Here is the screenshot: 
![screenshot from 2016-12-08 18-44-50](https://cloud.githubusercontent.com/assets/21028278/21018992/adf40c2a-bd77-11e6-9121-23986eda748b.png)

I don't know if this is a bug or an applet setting.
 Here is a screenshot of the applet settings as well:
![screenshot from 2016-12-08 18-55-30](https://cloud.githubusercontent.com/assets/21028278/21019109/04bd09da-bd78-11e6-82ac-22452de89d73.png)

Thank you for your time.

**Comment by mockturtl** [comment]
> Hello, I am sorry for making a new thread, but you closed the previous one 

You can still comment on closed issues.

> As you can see It is still not centered, so this is a problem with the applet and not the theme.

Cinnamon controls panel layout, not the individual applet.

**Comment by mockturtl** [comment]
This issue is now locked; please continue discussion on #170.
