### ISSUE TITLE
Weather data doesn't load until commenting out try-catch block in MyApplet.refreshWeather

### ISSUE THREAD

**Issue by jaszhix** [mockturtl/cinnamon-weather#177]
Linux Mint 18.1
Cinnamon 3.2.7
Weather 1.13.7

For some reason the applet only loads once on a fresh boot. If I restart Cinnamon or the applet, the http request never completes. When I comment out [this try-catch block](https://github.com/mockturtl/cinnamon-weather/blob/master/applet.js#L389), it works every time. I can see this might not be an issue if someone never restarts Cinnamon, but I think there must be a way to debug this. I see this in glass.log a lot every day:

```sh
error t=2017-01-01T18:08:03.469Z weather@mockturtl#: TypeError: json.get_object_member(...).get_object_member(...) is null
```

It seems like we could replace [this](https://github.com/mockturtl/cinnamon-weather/blob/master/applet.js#L369) with JSON.parse and have native formatting of the weather object. It would require rewriting all the lines accessing the object but would be a lot easier to read and debug.

When I import Main and add ```Main._logInfo(message.response_body.data)``` on L370, I see

```js
error t=2017-01-01T18:16:47.458Z weather@mockturtl#: TypeError: json.get_object_member(...).get_object_member(...) is null
info t=2017-01-01T18:17:30.414Z {"query":{"count":0,"created":"2017-01-01T18:17:30Z","lang":"en-US","results":null}}
```

So maybe when results is null, we could recurse the object for x amount of times, checking its value. I'm not sure why the request would return null, but I'm guessing its Soup's fault. I found [this](http://stackoverflow.com/questions/14806981/using-gjs-how-can-you-make-an-async-http-request-to-download-a-file-in-chunks), which also might be useful.

**Comment by sdgathman** [comment]
Using native parsing would effectively run code from an untrusted source (yahoo).  Do you really want yahoo running arbitrary javascript code in your cinnamon desktop?

**Comment by jaszhix** [comment]
I don't. Fortunately, that has nothing to do with this issue, nor is it possible as CJS can't run browser JS without modification.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
