### ISSUE TITLE
Stuck in "Loading"

### ISSUE THREAD

**Issue by kaqqao** [mockturtl/cinnamon-weather#182]
It's eternally stuck in "Loading" for me. The only reason I can come up with is that I have to connect to the internet through a proxy. Maybe the applet doesn't respect the Gnome proxy settings?

**Comment by mockturtl** [comment]
Hi @kaqqao, please note development has moved.

https://github.com/mockturtl/cinnamon-weather#notice-this-repository-is-no-longer-maintained

re: Gnome proxy settings, see #14.  You may find some useful information in that thread.
