### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by hcgpalm** [mockturtl/cinnamon-weather#31]
It would be nice if the applet had options to show;
1. Air pressure as metric hPa (mbar equivalent) or kPa (se http://en.wikipedia.org/wiki/Pascal_%28unit%29#Hectopascal_and_millibar_units)
2. Sunrise and sunset times in 24 hour format

**Comment by mockturtl** [comment]
1. @f2fa5cb252a7f6dbac0d783f2f674f1e655c7d98
1. @48104a56f19815ed89b4ff57959ce1b91c6f4015

@hcgpalm :+1: Done and done.  Thanks for the suggestion!
