### ISSUE TITLE
cinnamon-weather applet won't start

### ISSUE THREAD

**Issue by steevithak** [mockturtl/cinnamon-weather#43]
I've just installed Fedora 19 with the Cinnamon desktop. I added several applets successfully to the status bar but adding the weather applet doesn't work. No weather applet appears on the status bar, nor does any error message appear. I tried first going to the "configure" dialog in the applet installer and configured all the fields I could. There is no field to enter a geographical location, which seems odd. Also there is a field called "WOEID" with no indication as to what should go in it. There is a button above the field that says "Get WOEID", however clicking that button has no effect at all. Not sure if that's related to why the applet can't be added. There is no versioning information evident.

**Comment by AcostArichA** [comment]
Hi! I have LM 17.2. How can one make his native language to work for its applet? For me it is Russian. At settings I see only 'Translate condition' but its isn't translate at my language. Thank You.
