### ISSUE TITLE
"Not available" error message

### ISSUE THREAD

**Issue by geoffm** [mockturtl/cinnamon-weather#53]
Applet shows a big "Not available" label
![cinnamon weather not available](https://f.cloud.github.com/assets/901518/1739276/bf143a80-6397-11e3-9a7d-341e3c513f87.png)
additionnaly, the "Override location label" doesn't do anything.

**Comment by mockturtl** [comment]
> additionnaly, the "Override location label" doesn't do anything.

This is finally fixed. @6f5d27c853f7841bd1133cd9518c5907e85f4f01

> Applet shows a big "Not available" label

Merging this into #85.
